---
- name: Check if Swarm has already been initialized
  command: docker node ls
  register: swarm_status
  ignore_errors: true
  changed_when: swarm_status.rc != 0
  failed_when: swarm_status.rc != 0

- name: Add Docker node to existing Swarm as manager
  command: docker swarm join --token {{ hostvars[groups['swarm_managers'][0]]['worker_token']['stdout'] }} {{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:2377
  when: swarm_status.rc != 0