---
- name: Check if auto update is enabled
  stat:
    path: /etc/apt/apt.conf.d/20auto-upgrades
  register: autoupdate

- name: Disable auto update
  when: autoupdate.stat.exists
  become: true
  file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent

- name: Wait for any possibly running unattended upgrade to finish
  when: autoupdate.stat.exists
  become: true 
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: check for reboot request
  stat:
    path: /var/run/reboot-required
  register: reboot_request

- name: Remove cloud-init
  removes: /etc/cloud
  become: true
  block:
  - name: disable cloud-init
    file: 
      path: /etc/cloud/cloud-init.disabled
      state: touch
  - name: Reboot
    reboot:
  - name: uninstall package
    apt:
      name: cloud-init
      state: absent
      autoremove: yes
      purge: yes
  - name: remove folders
    file:
      state: absent
      path: "{{ item }}"
    loop:
    - /var/lib/cloud/
    - /etc/cloud

- name: Reboot host(s) after package upgrade
  become: true
  block:
    - name: Drain node
      docker_node:
        hostname: "{{ ansible_hostname }}"
        availability: drain
      ignore_errors: true
      register: drained
    - name: Wait end of drain process
      wait_for:
        timeout: 60
    - name: Reboot
      reboot:
        reboot_timeout: 60
    - name: Active node
      docker_node:
        hostname: "{{ ansible_hostname }}"
        availability: active
      when: drained is defined
  when: reboot_request.stat.exists

- name: Upgrade all packages to the latest version
  become: true 
  apt:
    name: "*"
    state: latest # noqa package-latest
    force_apt_get: true
    update_cache: yes

- name: Verify system dependencies
  become: true 
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - apache2-utils
      - avahi-daemon #required for local mDNS
      - network-manager
    state: latest # noqa package-latest
    force_apt_get: true
    update_cache: yes