---
galaxy_info:
  author: home-server
  description: Install and configure NUT (Network UPS Tools) server
  company: 
  license: MIT
  min_ansible_version: '2.10'
  platforms:
    - name: Debian
      versions: ['bullseye', 'bookworm']
    - name: Ubuntu
      versions: ['focal', 'jammy']
dependencies: []
