# code: language=ansible
---
# Docker image versions for Home Assistant role
homeassistant_version: "stable"
mosquitto_version: "2.0"
myelectricaldata_version: "latest"
faster_whisper_version: "latest"
frigate_version: "stable"
piper_version: "latest"
mosquitto_version: 2.0
esphome_version: stable
zigbee2mqtt_version: 2