# code: language=ansible
---
- name: Upgrade all packages to the latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest # noqa package-latest
    force_apt_get: true
    update_cache: true

- name: Check for reboot request
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_request

- name: Reboot host(s) after package upgrade
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: reboot_request.stat.exists

- name: Restic self update
  become: true
  ansible.builtin.command: restic self-update
  changed_when: true
...
