---
- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest # noqa package-latest
    force_apt_get: true
    update_cache: yes

- name: check for reboot request
  stat:
    path: /var/run/reboot-required
  register: reboot_request

- name: Reboot host(s) after package upgrade
  become: true
  reboot:
    reboot_timeout: 60
  when: reboot_request.stat.exists

- name: restic self update
  become: true
  shell: restic self-update