port: 5000
debug: true
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
# Par défaut le backend en local dans le /data/cache.db du conteneur.
# Mais il est possible de basculer sur une base de données externe de type SQLite ou PostgreSQL
# Exemple pour Postgres :
#storage_uri: postgresql://myelectricaldata:myelectricaldata@postgres:5432/myelectricaldata
tempo:
  enable: true
home_assistant: # WITH MQTT DISCOVERY
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws: # FOR ENERGY TAB
  enable: true
  ssl: false
  token: HOME_ASSISTANT_TOKEN_GENERATE_IN_PROFILE_TABS_(BOTTOM)
  url: homeassistant:8123
  max_date: "2021-06-01"
  purge: false
ssl:
  gateway: true
  certfile: ""
  keyfile: ""
influxdb:
  enable: false
  scheme: http
  hostname: influxdb
  port: 8086
  token: myelectricaldata
  org: myelectricaldata
  bucket: myelectricaldata
  # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
  # mais va augmenter la consommation mémoire & CPU et donc à activer uniquement sur un hardware robuste.
  method: synchronous    # Mode disponible : synchronous / asynchronous / batching
  # batching_options permet uniquement de configurer la methode `batching`.
  # Pour plus d'information : https://github.com/influxdata/influxdb-client-python#batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: mosquitto
  port: 1883
  username: null
  password: null
  prefix: myelectricaldata
  client_id: myelectricaldata     # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
#  ca_cert: /certs/ca.pem         # Certificate Authority a utiliser pour etablir une connection SSL au server MQTT
# Configuration SSL optionnel.
#ssl:
#  keyfile: "/data/key.pem"
#  certfile: "/data/cert.pem"
myelectricaldata:
