---
- name: Git fetch kresus
  git:
    repo: https://framagit.org/kresusapp/kresus
    dest: /home/{{ ansible_user }}/stacks/kresus/repo
    version: main

- name: Build kresus Image
  docker_image:
    build:
      pull: yes
      path: /home/{{ ansible_user }}/stacks/kresus/repo/support/docker
      dockerfile: /home/{{ ansible_user }}/stacks/kresus/repo/support/docker/Dockerfile-stable
    name: registry.leducd.duckdns.org/kresus
    tag: latest
    push: yes