---
- name: Install swarmpit on first swarm_manager
  when: inventory_hostname == groups['swarm_managers'][0]
  block:
  - name: Verify stacks directory exists
    file:
      path: "/home/{{ ansible_user }}/stacks"
      state: directory
      mode: 0644

  - name: Verify swarmpit volume path
    when: inventory_hostname == groups['swarm_managers'][0]
    become: true
    file:
      path: "{{ gluster_mount_path }}/{{ item }}"
      state: directory
      mode: 0644
    loop:
      - swarmpit-db
      - swarmpit-influx

  - name: Create docker-compose stack file
    template:
      src: docker-compose.yml
      dest: /home/{{ ansible_user }}/stacks/swarmpit-stack.yml
      mode: 0775

  - name: Deploy stack from a compose file
    docker_stack:
      state: present
      name: swarmpit
      compose:
        - /home/{{ ansible_user }}/stacks/swarmpit-stack.yml