network:
    ethernets:
        eht0:
            addresses:
            - 192.168.21.2/24
            gateway4: 192.168.21.1
            nameservers:
                addresses: [192.168.21.2, 192.168.21.1]
            optional: true
    version: 2