# code: language=ansible
---
# Default PostgreSQL version for Kresus
kresus_postgres_image: "postgres"
kresus_postgres_version: "15"
apprise_image: "caronc/apprise"
apprise_version: "1.3"
kresus_image: "bnjbvr/kresus"
kresus_version: "0.23.5"
