#jinja2: lstrip_blocks: True, trim_blocks: True
services:
  prometheus:
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_backend
      - traefik.constraint-label=traefik_backend
      - traefik.http.routers.prometheus-https.rule=Host(`prometheus.{{app_domain_name}}`)
      - traefik.http.routers.prometheus-https.entrypoints=https
      - traefik.http.routers.prometheus-https.tls=true
      - traefik.http.routers.prometheus-https.tls.certresolver=le
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.prometheus-https.middlewares=authentik@docker
    image: "{{ prometheus_image }}:{{ prometheus_version }}"
    volumes:
      - prometheus-conf:/etc/prometheus
      - prometheus-data:/prometheus
    command: 
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=200h
    networks:
      - backend
      - traefik_backend
      - authentik_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  alertmanager:
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_backend
      - traefik.constraint-label=traefik_backend
      - traefik.http.routers.alertmanager-https.rule=Host(`alertmanager.{{app_domain_name}}`)
      - traefik.http.routers.alertmanager-https.entrypoints=https
      - traefik.http.routers.alertmanager-https.tls=true
      - traefik.http.routers.alertmanager-https.tls.certresolver=le
      - traefik.http.services.alertmanager.loadbalancer.server.port=9090
      - traefik.http.routers.alertmanager-https.middlewares=authentik@docker
    image: "{{ alertmanager_image }}:{{ alertmanager_version }}"
    container_name: alertmanager
    volumes:
      - alertmanager-conf:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/alertmanager
    restart: unless-stopped
    networks:
      - backend
      - traefik_backend

  node-exporter:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: "{{ node_exporter_image }}:{{ node_exporter_version }}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      # Enable only essential collectors
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--no-collector.cpu.info'
      - '--collector.loadavg'
      - '--collector.meminfo'
      - '--collector.diskstats'
      - '--collector.filesystem'
      - '--collector.netdev'
      - '--collector.time'
      - '--collector.uname'
      - '--collector.thermal_zone'
    networks:
      - backend
    restart: always
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M

  grafana:
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_backend
      - traefik.constraint-label=traefik_backend
      - traefik.http.routers.grafana-https.rule=Host(`grafana.{{ app_domain_name }}`)
      - traefik.http.routers.grafana-https.entrypoints=https
      - traefik.http.routers.grafana-https.tls=true
      - traefik.http.routers.grafana-https.tls.certresolver=le
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    image: "{{ grafana_image }}:{{ grafana_version }}"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning
    user: "{{ getent_passwd[ansible_user].1 }}"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_DOMAIN: "grafana.{{ app_domain_name }}"
      GF_SERVER_ROOT_URL: "https://grafana.{{ app_domain_name }}"
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: "{{ grafana_mail_smtphost }}:{{ grafana_mail_smtpport }}"
      GF_SMTP_USER: "{{ grafana_mail_smtpname}}"
      GF_SMTP_PASSWORD: "{{ grafana_mail_smtppwd }}"
      GF_SMTP_FROM_ADDRESS: "{{ grafana_mail_from }}"

      # Generic OAuth
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ grafana_oauth_client_id }}" # TODO move to secret
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ grafana_oauth_client_secret }}" # TODO move to secret
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.{{ app_domain_name }}/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.{{ app_domain_name }}/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.{{ app_domain_name }}/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.{{ app_domain_name }}/application/o/end-session/"
      # User creation and sync settings
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME: "email"
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: "given_name"
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: "preferred_username"
      # Optionally map user groups to Grafana roles
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "(contains(groups[*], 'grafana-admin') || contains(group[*], 'grafana-admin')) && 'Admin' || (contains(groups[*], 'grafana-user') || contains(group[*], 'grafana-user')) && 'Editor' || (contains(groups[*], 'grafana-viewer') || contains(group[*], 'grafana-viewer')) && 'Viewer' || 'Viewer'"
    networks:
      - backend
      - traefik_backend
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  loki:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: "{{ loki_image }}:{{ loki_version }}"
    volumes:
      - loki-data:/loki
      - loki-config:/etc/loki
    networks:
      - backend
    restart: unless-stopped

  promtail:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: "{{ promtail_image }}:{{ promtail_version }}"
    volumes:
      - "/var/log:/var/log:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - promtail-conf:/etc/promtail/
    networks:
      - backend
    restart: unless-stopped

  cadvisor:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: "{{ cadvisor_image }}:{{ cadvisor_version }}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend
      - traefik_backend
    restart: always
    deploy:
      mode: global

  nextcloud-exporter:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: nextcloud-exporter
    image: "{{ nextcloud_exporter_image }}:{{ nextcloud_exporter_version }}"
    security_opt:
      - no-new-privileges:true
    command: nextcloud-exporter -c /conf/config.yml 
    volumes:
      - nextcloud_exporter_conf:/conf:ro
    restart: always
    networks:
      backend:
        aliases:
          - nextcloud-exporter

  {% if alertmanager_nextcloud_conversation_token is defined and alertmanager_nextcloud_conversation_token %}
  nextcloud-talk-bot:
    build:
      context: ./nextcloud-talk-bot
      dockerfile: Dockerfile
    container_name: nextcloud-talk-bot
    restart: unless-stopped
    environment:
      NC_URL: "https://{{ app_domain_name }}"
      TOKEN: "{{ alertmanager_nextcloud_conversation_token }}"
      SECRET: "{{ alertmanager_nextcloud_bot_secret }}"
    networks:
      - backend
  {% endif %}

  autoheal: # restart container when healthcheck is ko
    labels:
      - com.centurylinklabs.watchtower.enable={{ 'true' if autoheal_version != 'latest' else 'false' }}
    image: "{{ autoheal_image }}:{{ autoheal_version }}"
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 30   # check every 30 seconds
      AUTOHEAL_START_PERIOD: 120   # wait 120 seconds before first health check
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 60   # Docker waits max 60 seconds for a container to stop before killing during restarts
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  watchtower:
    labels:
      - com.centurylinklabs.watchtower.enable={{ 'true' if watchtower_version != 'latest' else 'false' }}
    image: "{{ watchtower_image }}:{{ watchtower_version }}"
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Daily at 4am
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN={{ watchtower_api_token }}
      - TZ=Europe/Paris
    {% if alertmanager_nextcloud_conversation_token is defined and alertmanager_nextcloud_conversation_token %}
      - WATCHTOWER_NOTIFICATION_URL=generic+http://nextcloud-talk-bot:81/send_message?template=json&disabletls=true
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      # - 'WATCHTOWER_NOTIFICATION_TEMPLATE={% raw %}{{- if .Report -}}{{- with .Report -}}{{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed{{- range .Updated}}\n- {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}{{- end -}}{{- range .Fresh}}\n- {{.Name}} ({{.ImageName}}): {{.State}}{{- end -}}{{- range .Skipped}}\n- {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}{{- end -}}{{- range .Failed}}\n- {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}{{- end -}}{{- end -}}{{- else -}}{{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}{{- end -}}{% endraw %}'
    {% else %}
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM={{ alertmanager_smtp_from }}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO={{ alertmanager_email_to }}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER={{ alertmanager_smtp_host }}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT={{ alertmanager_smtp_port | default(587) }}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER={{ alertmanager_smtp_user }}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD={{ alertmanager_smtp_password }}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    {% endif %}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    command: --label-enable

networks:
  traefik_backend:
    external: true
  authentik_backend:
    external: true
  backend:

volumes:
  loki-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ docker_volumes_path }}/loki-config"
  nextcloud_exporter_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ docker_volumes_path }}/nextcloud-exporter-conf"
  loki-data:
  alertmanager-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ docker_volumes_path }}/alertmanager-conf"
  grafana-data:
  grafana-provisioning:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ docker_volumes_path }}/grafana-provisioning"
  prometheus-data:
  prometheus-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ docker_volumes_path }}/prometheus-conf"
  promtail-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ docker_volumes_path }}/promtail-conf"
