# code: language=ansible
---
# Docker image versions for Monitoring role
prometheus_version: "v2.50.1"
alertmanager_version: "v0.27.0"
node_exporter_version: "v1.7.0"
grafana_version: "10.3.3"
loki_version: "2.9.4"
promtail_version: "2.9.4"
cadvisor_version: "v0.49.1"
