---
- name: Check if Swarm has already been initialized
  command: docker node ls
  register: swarm_status
  ignore_errors: true
  changed_when: swarm_status.rc != 0
  failed_when: swarm_status.rc != 0

- name: Initialize new Docker Swarm Leader
  command: docker swarm init --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
  when: swarm_status.rc != 0 and inventory_hostname == groups['swarm_managers'][0]
  run_once: true

- name: Get the Manager join-token
  command: docker swarm join-token --quiet manager
  when: inventory_hostname == groups['swarm_managers'][0]
  register: manager_token

- name: Get the worker join-token
  when: inventory_hostname == groups['swarm_managers'][0]
  command: docker swarm join-token --quiet worker
  register: worker_token