---
- name: Check if Gluster volume is initialized
  stat:
    path: "{{ gluster_volume_path }}/{{ inventory_hostname }}/brick"
  register: glustervolume

- name: Verify Gluster volume path
  become: true
  file:
    path: "{{ gluster_volume_path }}/{{ inventory_hostname }}/brick"
    state: directory
    mode: 0644

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    brick: "{{ gluster_volume_path }}"
    replicas: "{{ groups.gluster_nodes | count() }}"
    cluster: "{{ groups.gluster_nodes | join(',') }}"
    host: "{{ inventory_hostname }}"
    rebalance: yes
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted