---
- name: Install Gluster and dependencies
  become: true
  apt:
    pkg:
      - xfsprogs
      - attr
      - glusterfs-server
      - glusterfs-common
      - glusterfs-client
    state: present
    force_apt_get: true
    update_cache: yes

- name: Enable Gluster service
  become: true 
  systemd:
    name: glusterd
    enabled: yes
    state: started